import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useRouter } from "next/navigation";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Link } from "lucide-react";
import SideMenu from "./SideMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Movie",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const res = await fetch(
    "http://worldtimeapi.org/api/timezone/Asia/Hong_Kong",
    {
      cache: "no-cache",
    }
  );
  const data = await res.json();

  return (
    <html lang="en" className="dark    ">
      <body className={inter.className}>
        <div className="border-b ">
          <div className=" flex h-16 items-center px-4 container mx-auto">
            <div>Movie App</div>
            <div>
              {data.datetime} {data.abbreviation}
            </div>
            <div className="ml-auto flex items-center space-x-4">
              <Avatar>
                <AvatarImage src="https://avatars.githubusercontent.com/u/1004701?v=4" />
                <AvatarFallback>CN</AvatarFallback>
              </Avatar>
            </div>
          </div>
        </div>
        <div className=" flex">
          <SideMenu />
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
