import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
function SideMenu() {
  return (
    <div className="pb-12 w-1/4">
      <div className="space-y-4 py-4 ">
        <div className="px-3 py-2">
          <h2 className="mb-2 px-4 text-lg font-semibold tracking-tight">
            Discover
          </h2>
          <div className="space-y-1">
            <Button variant="secondary" className="w-full justify-start">
              Movie
            </Button>
            <Button variant="ghost" className="w-full justify-start">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
                className="mr-2 h-4 w-4"
              >
                <rect width="7" height="7" x="3" y="3" rx="1" />
                <rect width="7" height="7" x="14" y="3" rx="1" />
                <rect width="7" height="7" x="14" y="14" rx="1" />
                <rect width="7" height="7" x="3" y="14" rx="1" />
              </svg>
              Browse
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const res = await fetch(
    "http://worldtimeapi.org/api/timezone/Asia/Hong_Kong",
    {
      cache: "no-cache",
    }
  );
  const data = await res.json();

  return (
    <html lang="en" className="dark    ">
      <body className={inter.className}>
        <div className="border-b ">
          <div className=" flex h-16 items-center px-4 container mx-auto">
            <div>Jacky App</div>
            <div>
              {data.datetime} {data.abbreviation}
            </div>
            <div className="ml-auto flex items-center space-x-4">
              <Avatar>
                <AvatarImage src="https://avatars.githubusercontent.com/u/1004701?v=4" />
                <AvatarFallback>CN</AvatarFallback>
              </Avatar>
            </div>
          </div>
        </div>
        <div className=" flex">
          <SideMenu />
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
